In [1]:
import torch as t
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Introduction to tensors

### Creating tensors

PyToarch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = t.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Vector
vector = t.tensor([7,7])
vector

tensor([7, 7])

In [6]:
# number of [] is how many dimensions
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = t.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = t.tensor([[[1,2,3],
                        [3,4,5],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [7, 8, 9]])

### Random tensors

Why random tensors?

Random tensors are importnat becasue the way many nn learn is that they start with tesnors fill of random numbers and the nadjust those random numbers to better represetn the data.

Start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers

torch.rand --> https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
### Create a random tensor of size (3,4)
random_tensor = t.rand(3,4)
random_tensor

tensor([[0.1044, 0.3604, 0.0290, 0.4126],
        [0.7905, 0.1277, 0.4889, 0.1237],
        [0.6377, 0.2223, 0.2537, 0.6241]])

In [17]:
random_tensor.ndim

2

In [18]:
# Create a ranomd tensor with smiliar shape to an image tensor
random_image_size_tensor = t.rand(size = (224,224,3)) #height, width, color channels(R,G,B)
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### Zero and ones

In [19]:
# Create a tensor of all zeros
zeros = t.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# Create a tensor of all oens
ones = t.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a rang of tensors and tensors-like

In [21]:
# Use torch.range()(.range() is gettinge deleted so used .arange)
zero_to_nine = t.arange(0,10)
zero_to_nine

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
t.arange(start=0, end=1000, step = 80)

tensor([  0,  80, 160, 240, 320, 400, 480, 560, 640, 720, 800, 880, 960])

In [23]:
# Createing tensors like
ten_zeros = t.zeros_like(input=zero_to_nine)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes is one of the 3 big error ull run into with deep learning:
1. Tensors not right datatpe
2. Tensors not right shapre
3. Tensors not on the right device

In [24]:
# Floar 32 tensor(deafult data type float 32)
float_32_tensor = t.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what dataype is the tensor (32-bit flaoing point(singel precision, deafult) and 16-bit floating point)(measure of the detail in which the quality is expressed)
                                             # sacrifie detail for speed but can go even slower with higer detail in 64-bit
                               device = None, # CPU by defult, GPU faster(cuda)
                               requires_grad = False) # track a gradint of the tensor operations)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [25]:
float_16_tensor = float_32_tensor.type(t.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
int_32_tensor = t.tensor([3,6,9], dtype=t.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensores(tensor attributes)

1. to get datatype use 'tensor.dtype'
2. to get shape use 'tensor.shape'
3. to get devices use 'tensor.device'

In [28]:
foo = t.rand(4,4, dtype=t.float16)
foo

tensor([[0.4053, 0.2832, 0.5771, 0.2173],
        [0.1714, 0.8530, 0.1367, 0.8027],
        [0.6558, 0.8770, 0.3574, 0.9956],
        [0.0796, 0.5371, 0.8833, 0.4219]], dtype=torch.float16)

In [29]:
# Find out details
print(foo)
print()
print("Datatype of tensor: ", foo.dtype)
print("Shape of tensor: ", foo.shape)
print("Device of tenor: ", foo.device)

tensor([[0.4053, 0.2832, 0.5771, 0.2173],
        [0.1714, 0.8530, 0.1367, 0.8027],
        [0.6558, 0.8770, 0.3574, 0.9956],
        [0.0796, 0.5371, 0.8833, 0.4219]], dtype=torch.float16)

Datatype of tensor:  torch.float16
Shape of tensor:  torch.Size([4, 4])
Device of tenor:  cpu


In [30]:
foo.size(), foo.shape

(torch.Size([4, 4]), torch.Size([4, 4]))

### Manipulating Tensors (tensor operation)

Tensor operation:
1. ADDITION
2. SUBSTRATION
3. MULTIPLICATION (ELEMENT-WISE)
4. DIVISION
5. MATRIX MULTIPLICATION

In [41]:
# Create a tensor and add 10
tensor = t.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])


In [42]:
# Multiply by 10
tensor * 10

tensor([110, 120, 130])

In [43]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [45]:
# Try out pytorch in built functions
t.mul(tensor, 10) # multiply

tensor([10, 20, 30])

In [46]:
t.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing mul in nn and deep learning
1. Element wise
2. Matrix wise (dot product)

An m × n matrix: the m rows are horizontal and the n columns are vertical.

**R X C**

There are two main rules that performing matrix mul needs to satisfy:
1. The **inner dimineions** must match
2. The resulting matrix has the shape of the **outer dimiensions**

cool website visualization --> matrixmultiplication.xyz

In [48]:
# Element wise mul
print(tensor, "*", tensor)
print(f"Equals:", {tensor * tensor})

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: {tensor([1, 4, 9])}


In [54]:
#Matrix mul
t.matmul(tensor, tensor) # u can also use @

tensor(14)

In [55]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 1.85 ms


In [56]:
%%time
t.matmul(tensor, tensor) # torches implementation is usually faster + less code

CPU times: user 127 µs, sys: 0 ns, total: 127 µs
Wall time: 134 µs


tensor(14)

### One of the most common errors in dl: shape errors



In [66]:
# shapes for matrix mul
tensor_A = t.tensor([[1,2],
                    [3,4],
                    [5,6]])

tensor_B = t.tensor([[7,10],
                     [8,11],
                     [9,12]])

#t.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: ignored

To fix tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**

A **trenspose** switches the axes or dim of a given tensor

In [68]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [69]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [73]:
# The matix mul operation works when tensor_B is transposed
t.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max. mean, sum, etc (tensor aggreggation)

In [79]:
# Create a tensor
x = t.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [80]:
#Fin the min
t.min(x), x.min()

(tensor(0), tensor(0))

In [81]:
#Find the max
t.max(x), x.max()

(tensor(90), tensor(90))

In [82]:
#Find the mean - note: t.mean() deos not work with dtype long
#t.mean(x)

RuntimeError: ignored

In [88]:
t.mean(x, dtype = t.float32), x.type(t.float32).mean, x.type(t.float32).mean()

(tensor(45.), <function Tensor.mean>, tensor(45.))

In [89]:
#Find the sum
t.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the position min and max

In [93]:
# Find the postion in tensor that has the min value in argmin() --> return index posiont of target tensor where the min value occurs
x.argmin(), t.argmin(x)

(tensor(0), tensor(0))

In [95]:
x.argmax(), t.argmax(x)

(tensor(9), tensor(9))

In [96]:
x[9]

tensor(90)

### Reshaping, stakcing, squeezing and unsquezzing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memoory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all 1 dim from a tensor
* Unsqueeze - add a 1 dim to a target tesnor
* Permute - return a view of the input with dimesnion permuted(swapped) in a certain way


In [152]:
# Let's create a tensor
x = t.arange(1. ,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [153]:
# Add an extra dimeions(reshape), needs to be compatible wtih the og shape
x_reshaped = x.reshape(1,10) # could be (10,1), could be (2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [154]:
# Change the view
z = x.view(1, 10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [155]:
# Changing z changes x (because a view of a tensor share the same memory as teh og input)
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [156]:
#Stack tensors on top of each other
x_stacked = t.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [157]:
x_stacked = t.stack([x, x, x, x], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [158]:
# Verticaly stacks the tensors on top each otehr in diff []
x_stacked = t.vstack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [159]:
# adds tensors one after another in one []
x_stacked = t.hstack([x,x,x,x])
x_stacked, x_stacked.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,
          5.,  6.,  7.,  8.,  9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
          9., 10.,  5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([40]))

In [162]:
# torch.squeeze --> return a tensor with all of the dimenzion size one removed
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [166]:
x_squeezed = x_reshaped.squeeze()
x_squeezed, x_squeezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [169]:
# torch.unsqueeze() - adds a single dim to a target tesnor at a specific dim
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dim = x, where the dim will be added
x_unsqueezed, x_unsqueezed.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [171]:
# torch.permute - rearranges the dim of a target tensor in a specified order (popular with immages)
x_original = t.rand(size=(224,244,3))

# Permute the og tensor to rearrange the axis(or dim) order
x_permuted = x_original.permute(2,0,1) # shifted axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
# since this is just different view it is stored in the same memory

Previous shape: torch.Size([224, 244, 3])
New shape: torch.Size([3, 224, 244])


### Indexing(selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [185]:
import torch as t
# Create a tensor
x = t.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [186]:
# Lets index on our new tensor
# first dim(dim = 0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [187]:
# second dim(dim = 1)
x[0,0]

tensor([1, 2, 3])

In [189]:
# third dim(dim= 2)
x[0,2,2]

tensor(9)

In [190]:
# you can also use ":" to select "all" of a target dim
x[:, 0]

tensor([[1, 2, 3]])

In [191]:
# Get all values of 0th adn 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [193]:
# Get all values of the 0 dim but only 1 index values of 1st and 2nd dim
x[:, 1,1], x[0, 1,1]

(tensor([5]), tensor(5))

In [194]:
# Get index 0 of 0th and 1st dim and all values of 2nd dim
x[0,0,:]

tensor([1, 2, 3])

### PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical comupting library.

And becasue of this, Pytorch has huncionlity to interact with it.
* Data in NumPy, want in PyTorch tensor -> "torch.from_numpy(ndarray)"
* PyTorch tensor --> NumPy --> "torch.Tensor.numpy()"

In [205]:
# NumPy array to tensot
import torch as t
import numpy as np

array = np.arange(1.0, 8.0)
tensor = t.from_numpy(array) #.type(t.float32) # defult numpy dtype is float 64 so change to float 32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [206]:
array.dtype

dtype('float64')

In [207]:
t.arange(1.0, 8.0).dtype

torch.float32

In [208]:
# Change teh value of array, what will this do to tensor? does not change
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [215]:
# Tensor to NumPy array
tensors_s = t.ones(7)
numpy_tensor = tensors_s.numpy() # reflects the original dtype
tensors_s, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [213]:
# Change the tensor, what happens to numpy_tensor?
tensors_s = tensors_s + 1
tensors_s, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

In short how a nn learns:

1. Start with random numbers
2. Tensor operations
3. Update random numbers to try and make them better represnetation of the data
4. again
5. again
6. again

To reduce the randomness in nn and PyTorch comes the concept of a **random seed**.

Essentailly what the random seed does is "flavour" the randomness.

In [219]:
# Create two random tensors
rand_tensor_a = t.rand(3,4)
rand_tensor_b = t.rand(3,4)

print(rand_tensor_a)
print(rand_tensor_b)
print(rand_tensor_a == rand_tensor_b)

tensor([[0.0470, 0.2096, 0.2246, 0.4924],
        [0.0032, 0.2133, 0.1510, 0.5790],
        [0.0661, 0.3298, 0.9006, 0.5774]])
tensor([[0.6934, 0.7092, 0.0393, 0.3706],
        [0.1806, 0.1040, 0.9856, 0.9638],
        [0.3183, 0.7995, 0.1383, 0.1153]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [1]:
# Lets make some random byt reproducible tensors
import torch as t

# Set the random seed
RANDOM_SEED = 42 #0, 1234 are popoular
t.manual_seed(RANDOM_SEED) # only works for one radomness
rand_tensor_C = t.rand(3,4)

t.manual_seed(RANDOM_SEED)
rand_tensor_D = t.rand(3,4)

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objesct on the GPUs(and making faster computations)

GPUs = faster computation on numbers, thanks to CUBA + NVIDIA hardware + PyTorach working behind the scenes

1. Getting a GPU

  Easiest - Use Google Colab for a gree GPU(!nvidia-smi)

  Use your own GPU - takes alittle bit of setup and requires you to buy one

  Use cloud computing - GCP, AWS, Azure, these services allow you to rent
  computer on the cloud and access them

2. Check for GPU access with PyTorch

  Check for GPU access with PyToarch --> t.cuda.is_available()

  Setup device agnostic code --> device = "cuda" if torch.cuda.is_available() else "cpu"

  Count number of devices --> torch.cuda.device_cound()

3. Putting tensors and models on the GPU

  The reason we want out rensors/models on the GPU is beacsuse usign a GPU results in faster computations.

4. Moving tensors back to the CPU

  If tensor is on GPU, can not transorm it to NumPy.

  To fix the GPU tensor with NumPy issue, we can first set it to the CPU --> .cpu().numpy()


In [4]:
#Putting tensor and (models) on the GPU
tensor = t.tensor([1,2,3], device = "cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU(if avaiable)
device = "cuda" if t.cuda.is_available() else "cpu"
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [8]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])